name: CI Pipeline ETL Fraud Detection

# Workflow's activate events: push code request or pull request on main branch
on:
  push:
    branches: ["main"]    # Run CI test when have a push request on main branch
  pull_request:
    branches: ["main"]    # Run CI test when have a pull request on main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use Ubuntu VM for a runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Pull code from repository to runner

      - name: Set up Python
        uses: actions/setup-python@v4  # Setting python on runner
        with:
          python-version: "3.10"      # Sellect Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   

      - name: Run ETL pipeline script
        run: python etl_pipeline.py   # Run pipeline to certain it not error

      - name: Run unit tests
        run: pytest -v                # Run Pytest for CI test
